[Icon Theme]
Name=GNU-Darwin Aqua icons
Comment=Period desktop assets and original application branding without tiles
Inherits=Papirus,hicolor
Directories=128x128/apps,128x128/devices,128x128/mimetypes,128x128/places,16x16/apps,16x16/devices,16x16/mimetypes,16x16/places,22x22/apps,22x22/devices,22x22/mimetypes,22x22/places,24x24/apps,24x24/devices,24x24/mimetypes,24x24/places,32x32/apps,32x32/devices,32x32/mimetypes,32x32/places,48x48/apps,48x48/devices,48x48/mimetypes,48x48/places,scalable/apps,scalable/devices,scalable/mimetypes,scalable/places

[128x128/apps]
Size=128
Type=Fixed
Context=Applications

[128x128/devices]
Size=128
Type=Fixed
Context=Devices

[128x128/mimetypes]
Size=128
Type=Fixed
Context=MimeTypes

[128x128/places]
Size=128
Type=Fixed
Context=Places

[16x16/apps]
Size=16
Type=Fixed
Context=Applications

[16x16/devices]
Size=16
Type=Fixed
Context=Devices

[16x16/mimetypes]
Size=16
Type=Fixed
Context=MimeTypes

[16x16/places]
Size=16
Type=Fixed
Context=Places

[22x22/apps]
Size=22
Type=Fixed
Context=Applications

[22x22/devices]
Size=22
Type=Fixed
Context=Devices

[22x22/mimetypes]
Size=22
Type=Fixed
Context=MimeTypes

[22x22/places]
Size=22
Type=Fixed
Context=Places

[24x24/apps]
Size=24
Type=Fixed
Context=Applications

[24x24/devices]
Size=24
Type=Fixed
Context=Devices

[24x24/mimetypes]
Size=24
Type=Fixed
Context=MimeTypes

[24x24/places]
Size=24
Type=Fixed
Context=Places

[32x32/apps]
Size=32
Type=Fixed
Context=Applications

[32x32/devices]
Size=32
Type=Fixed
Context=Devices

[32x32/mimetypes]
Size=32
Type=Fixed
Context=MimeTypes

[32x32/places]
Size=32
Type=Fixed
Context=Places

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[48x48/devices]
Size=48
Type=Fixed
Context=Devices

[48x48/mimetypes]
Size=48
Type=Fixed
Context=MimeTypes

[48x48/places]
Size=48
Type=Fixed
Context=Places

[scalable/apps]
Size=64
Type=Scalable
Context=Applications
MinSize=16
MaxSize=256

[scalable/devices]
Size=64
Type=Scalable
Context=Devices
MinSize=16
MaxSize=256

[scalable/mimetypes]
Size=64
Type=Scalable
Context=MimeTypes
MinSize=16
MaxSize=256

[scalable/places]
Size=64
Type=Scalable
Context=Places
MinSize=16
MaxSize=256
